export const actions = {
	FETCH_START: 'FETCH_START',
	FETCH_SUCCESS: 'FETCH_SUCCESS',
	FETCH_ERROR: 'FETCH_ERROR',

	DELETE_START: 'DELETE_START',
	DELETE_SUCCESS: 'DELETE_SUCCESS',
	DELETE_ERROR: 'DELETE_ERROR',

	SET_PAGE: 'SET_PAGE',
};
